### PR TITLE
Adapt to new Service Delivery client and examples

### PR DESCRIPTION
**Pull request by miguelcardo**
Instead of just transceiving one command, request a service the example Service Provider, letting the caller choose between contactless card and Device Fidelity microSD.

### CODE REVIEW

**Comment by miguelcardo** [comment]
@petter-fidesmo Here we go...

**Comment by miguelcardo** [comment]
Pending (for Monday):
- code cleanup
- why does the Fidesmo App stay on the foreground after the service has been delivered? [might be something to change there]

**Comment by miguelcardo** [comment]
@petter-fidesmo Ready for review!

**Comment by ghost** [comment]
@miguelcardo :+1:

**Pull request merged**
