### PR TITLE
Reintroduce screen using the Transceive API

### PR DESCRIPTION
**Pull request by miguelcardo**
This example shall use all the actions exposed by the Fidesmo App, so let's recover the screen in which the user types the UUID manually (now called "OperationID") and the APDUs are fetched and delivered to the card/microSD.

The resulting example app (to be renamed, see comments to issue #8 ) will have three screens:
- Landing Activity, with two buttons (Service Delivery and Transceive examples)
- TransceiveExample Activity - the old one
- ServiceDeliveryExample Activity - the existing one

### CODE REVIEW

**Comment by miguelcardo** [comment]
@petter-fidesmo Ready for review!

**Comment by ghost** [comment]
@miguelcardo :+1:

**Pull request merged**
