### PR TITLE
Rename app to Android Service Delivery Demo

### LINKED ISSUE #12: Change app labels and screenshots to new repo name
"Android Transceive Demo", as the former name, should not appear in screenshots and app-name banner

### PR DESCRIPTION
**Pull request by miguelcardo**
This pull request implements issue #12 but due to the change of repo name, the 'hub' command is unable to turn that issue into a pull request, so I'll close #12 when this thing is merged.

### CODE REVIEW

**Comment by miguelcardo** [comment]
@slomo Ready for review!

**Comment by slomo** [comment]
The changes are definitely a :+1: but I was asking myself whether the package name should not also be changed.

**Comment by miguelcardo** [comment]
I'll change the package names too. Good idea!

**Comment by miguelcardo** [comment]
Package renamed. @slomo do you want to review it, or shall I squash & merge?

**Comment by slomo** [comment]
looks good to me :+1:

**Pull request merged**
